### ISSUE TITLE
Support for multiple aignement and undo assignment.

### ISSUE THREAD

**Issue by jeancroy** [n-riesco/v8stack#1]
First thanks for making this.
I beleive from the atom thread it is suppose to support case like this.
https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L102

```
original = Error.prepareStackTrace
Error.prepareStackTrace = function(e, stack){/* do something */}
Error.stack

Error.prepareStackTrace = original.
```

The problem is that `Error.prepareStackTrace` alwais return `v8stackPrepareStackTrace`
Then `Error.prepareStackTrace = original` makes `prepareStackTrace = v8stackPrepareStackTrace`

and basically from there v8stackPrepareStackTrace call itself until stack is exhausted.
https://github.com/n-riesco/v8stack/blob/master/index.js#L95-L96

There is a guard but only on calling hijack.
https://github.com/n-riesco/v8stack/blob/master/index.js#L51

**Comment by jeancroy** [comment]
But in general the module will only works up to a single override I believe.

**Comment by jeancroy** [comment]
I played a bit with the wrapping idea.
I believe this cover most cases.
https://gist.github.com/jeancroy/5e0372dc4dbf03000e28

Also i'm not sure about the idea of simply having a pointer to the stack object.
Because some package like cofeescript modify the object and atom is trying to get original object.

So either the privileged caller is called first when a stack happens, or we make a deep copy for later use.

**Comment by n-riesco** [comment]
@jeancroy

Thank you for reporting this issue. I should've checked that `v8stack` works with `bindings`. I fixed the issue by pausing the hijack during the evaluation of `error.stack`.

I like the approach you came up with [there](https://gist.github.com/jeancroy/5e0372dc4dbf03000e28). I've opened issue #2 to continue the discussion about this approach.
